version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boundary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  db-init:
    image: hashicorp/boundary:0.1.8
    command: ["database", "init", "-config", "/boundary/controller.hcl"]
    volumes:
      - "${PWD}/:/boundary/"
    environment:
      - BOUNDARY_PG_URL=postgresql://postgres:postgres@db/boundary?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  controller:
    image: hashicorp/boundary:0.1.8
    command: ["server", "-config", "/boundary/controller.hcl"]
    volumes:
      - "${PWD}/:/boundary/"
    hostname: boundary
    ports:
      - "9200:9200"
      - "9201:9201"
      - "9202:9202"
    environment:
      - BOUNDARY_PG_URL=postgresql://postgres:postgres@db/boundary?sslmode=disable
      - HOSTNAME=boundary
    depends_on:
      - db-init
    healthcheck:
      test: ["CMD", "curl", "-f", "http://boundary:9200"]
      interval: 3s
      timeout: 10s
      # start_period: 10s
      retries: 5

  # worker:
  #   image: hashicorp/boundary:0.1.8
  #   command: ["server", "-config", "/boundary/worker.hcl"]
  #   volumes:
  #     - "${PWD}/:/boundary/"
  #   hostname: worker
  #   expose:
  #     - "9200"
  #     - "9201"
  #     - "9202"
  #   environment:
  #     - HOSTNAME=worker
  #   depends_on:
  #     - controller
  #   # healthcheck:
  #   #   test: ["CMD", "curl", "-f", "http://boundary:9200"]
  #   #   interval: 3s
  #   #   timeout: 10s
  #   #   # start_period: 10s
  #   #   retries: 5

# I don't like this pattern :/

  worker1:
    image: hashicorp/boundary:0.1.8
    command: ["server", "-config", "/boundary/worker1.hcl"]
    volumes:
      - "${PWD}/:/boundary/"
    hostname: worker1
    expose:
      - "9200"
      - "9201"
      - "9202"
    environment:
      - HOSTNAME=worker1
    depends_on:
      - controller
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://boundary:9200"]
    #   interval: 3s
    #   timeout: 10s
    #   # start_period: 10s
    #   retries: 5

  worker2:
    image: hashicorp/boundary:0.1.8
    command: ["server", "-config", "/boundary/worker2.hcl"]
    volumes:
      - "${PWD}/:/boundary/"
    hostname: worker2
    expose:
      - "9200"
      - "9201"
      - "9202"
    environment:
      - HOSTNAME=worker2
    depends_on:
      - controller
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://boundary:9200"]
    #   interval: 3s
    #   timeout: 10s
    #   # start_period: 10s
    #   retries: 5

# Private Database Targets - not exposed to host network, only available via Boundary
  cassandra:
    image: bitnami/cassandra:latest

  mysql:
    image: mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=my-secret-pw'

  redis:
    image: redis

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=yourStrong(!)Password'
