version: "3.8"

networks:
  default:
  worker1:
  worker2:

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boundary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 5

  db-init:
    image: hashicorp/boundary:0.2.0
    command: ["database", "init", "-config", "/boundary/controller.hcl"]
    volumes:
      - "${PWD}/:/boundary/"
    environment:
      - BOUNDARY_PG_URL=postgresql://postgres:postgres@db/boundary?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  controller:
    image: hashicorp/boundary:0.2.0
    # command: ["server", "-config", "/boundary/controller.hcl"]
    entrypoint: sh -c "sleep 3 && exec boundary server -config /boundary/controller.hcl"
    volumes:
      - "${PWD}/:/boundary/"
    hostname: boundary
    ports:
      - "9200:9200"
      - "9201:9201"
    environment:
      - BOUNDARY_PG_URL=postgresql://postgres:postgres@db/boundary?sslmode=disable
    depends_on:
      - db-init
    networks:
      - default
      - worker1
      - worker2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9200"]
      interval: 3s
      timeout: 10s
      start_period: 10s
      retries: 5

  worker1:
    image: hashicorp/boundary:0.2.0
    command: ["server", "-config", "/boundary/worker1.hcl"]
    volumes:
      - "${PWD}/:/boundary/"
    hostname: worker1
    ports:
      - "9202:9202"
    environment:
      - HOSTNAME=worker1
    depends_on:
      - controller
    networks:
      - default
      - worker1

  worker2:
    image: hashicorp/boundary:0.2.0
    command: ["server", "-config", "/boundary/worker2.hcl"]
    volumes:
      - "${PWD}/:/boundary/"
    hostname: worker2
    ports:
      - "9203:9202"
    environment:
      - HOSTNAME=worker2
    depends_on:
      - controller
    networks:
      - default
      - worker2

# Private Database Targets - not exposed to host network, only available via Boundary

  postgres:
    image: postgres
    networks:
      - worker1
    environment:
      - POSTGRES_DB=test1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=my-secret-pw'
    networks:
      - worker2

  redis:
    image: redis
    networks:
      - worker2